name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: "change to your name"
      USER_EMAIL: "change to your email"
      PUBLISH_DIR: ./dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Commit files
        run: |
          mkdir $PUBLISH_DIR
          cp -r src/* $PUBLISH_DIR/
          cd $PUBLISH_DIR
          git init
          git config --local user.email $USER_EMAIL
          git config --local user.name $USER_NAME
          git status
          git remote add origin https://$SECRET@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy to Github pages"
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.
